feat/bottomAppBar
Joao-Pedro-P-Holanda/sustainow pull request #29
Opened 2024-11-25 00:43 UTC by erickgabrielfg

- Add bottomBar and routes of the app

- Add dependencies for Matherial icons

- Add Route class

2024-11-25 12:09 UTC, Joao-Pedro-P-Holanda requested changes

2024-11-25 12:09 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/MainActivity.kt
> +
Navegação dentro de cada subrota não vai usar strings, mas outros objetos serializáveis, que nem na rota Authentication. 

Criar novos objetos para as rotas iniciais e deixar o composable deles em branco por enquanto, aplicação não inicializa se a rota não puder ser encontrada.
```kotlin
composable<Objeto> {
}
```` 
Rota inicial de Consumption pode ser `ConsumptionMainPage`, de CollectiveActions `SearchCollectiveActions` e de Routines `ViewRoutine`

2024-11-25 12:09 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/MainActivity.kt
> +                    Route("Routines", "Routines", Icons.Default.Today),
Mudar atributo Content de cada rota para ser um objeto serializável, comentário abaixo dá exemplos desses objetos

2024-11-25 12:09 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/MainActivity.kt
Atualizar com as adições na branch principal

2024-11-26 13:33 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-11-26 13:33 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/MainActivity.kt
> +                        NavigationBar (
Adicionar checagens igual na topBar, bottomBar aparecendo na tela de login

2024-11-26 13:33 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/MainActivity.kt
> +                        navigation<Consume>(startDestination = ConsumptionMainPage){
Erro inesperado ocorrendo no login, talvez algo nas rotas tenha afetado o redirecionamento. Tive um problema parecido na hora de implementar o botão de voltar, mas é só um chute.

2024-11-26 14:07 UTC, Joao-Pedro-P-Holanda approved these changes

2024-11-26 15:02 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-11-26 15:02 UTC, merged