feat: carousel
Joao-Pedro-P-Holanda/sustainow pull request #39
Opened 2024-12-10 23:39 UTC by Francisco-Paulino-Arruda-Filho

feat: carousel

2024-12-11 11:57 UTC, Joao-Pedro-P-Holanda requested changes

2024-12-11 11:57 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/domain/model/LabeledImage.kt
> +    val image: Int,
Manter imagem como Bitmap para manter o encapsulamento, existem formas de converter o recurso para Bitmap

https://stackoverflow.com/questions/8717333/converting-drawable-resource-image-into-bitmap

2024-12-11 11:57 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/HomeScreen.kt
Adicionar algum conteúdo em vídeo, o vídeo pode reproduzir em loop enquanto estiver em destaque. E o label e supportingText também aparecem
[Vídeo sobre exoplayer](https://www.youtube.com/watch?v=JX1fwti2LI4)

2024-12-11 11:57 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/HomeScreen.kt
> +        LabeledImage(R.drawable.economiaenergia, "Economia de energia", "Economia de energia"),
utilizar recursos de string para os textos também

2024-12-11 20:34 UTC, Joao-Pedro-P-Holanda requested changes

2024-12-11 20:34 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/HomeScreen.kt
> +            supportingText = "Vídeo fogueira"
Vídeo não está utilizando recursos de string

2024-12-11 20:34 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/HomeScreen.kt
Elementos estão centralizados na tela, mas a visualização no protótipo posiciona o carousel no topo,  alterar `verticalArrangement = Arrangement.Center` na Coluna mais externa para posicionar a partir do topo verticalmente,

2024-12-11 20:34 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/HomeScreen.kt
>  }
Vídeo mostra um fundo preto repetidamente, mas durante a reprodução em qualquer outra ferramenta isso não ocorre, problema deve estar na configuração do player.

exoPlayer está sendo usado com remember, talvez movê-lo pro escopo do viewmodel auxilie
https://github.com/user-attachments/assets/38555dbb-8a7f-4584-b7c3-9129569e0b39

2024-12-11 23:58 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/MainActivity.kt
O topBar precisa dessa propriedade, mesmo que vazia

2024-12-11 23:59 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/presentation/ui/HomeScreen.kt
>  }
Normal por aqui

2024-12-12 00:03 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/MainActivity.kt
Basta remover o texto, o title pode continuar com a logo que já existe

2024-12-12 00:05 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/MainActivity.kt
![image](https://github.com/user-attachments/assets/4078208d-53aa-4922-9d9c-02dfbbc965a1)

2024-12-12 00:32 UTC, Joao-Pedro-P-Holanda approved these changes

2024-12-12 00:32 UTC, merged