feat/multiFieldQuestionCard
Joao-Pedro-P-Holanda/sustainow pull request #42
Opened 2024-12-13 17:20 UTC by erickgabrielfg

- Create MultiFieldQuestionCard
Obs: not yet finished

2024-12-13 18:17 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2024-12-13 18:17 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                BasicTextField(
Usar textfield ao invés de basic textField, valores inseridos não são renderizados

2024-12-13 18:17 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                BasicTextField(
Trocar por só textfield

2024-12-13 18:17 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                BasicTextField(
Trocar por só textfield

2024-12-13 18:17 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +            DropdownMenu(
Opções não renderizam

2024-12-13 18:21 UTC, Francisco-Paulino-Arruda-Filho requested changes

2024-12-13 18:21 UTC, Francisco-Paulino-Arruda-Filho commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +        Column (
Placeholder não some ao digitar

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda requested changes

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                        value = if(!isExpanded) "Qnt" else "${items.alternatives.size}",
Valor do textifeld não atualiza ao digitar com o menu não expandido

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                        value = if(!isExpanded) "Valor (W)" else "${items.alternatives.sumOf{ it.value.toDouble() } / items.alternatives.size}",
Utilizar recurso de string, especificar a unidade da questão ainda não precisa ser feito então pode apenas mostrar que é o total

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +    isRealConsumption: Boolean
Flag pode ser renomeada para editableNames

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                                        )
Não existe um manipulamento de erros, aplicação crasha se a duração não for válida. Mostrar supportingText de apoio quando a duração não for válida

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
Componente não possui nenhuma forma de acessar as respostas dele externamente, adicionar callbacks onAnswerAdded e onAnswerUpdated que recebem um FormAnswer e não retornam nada. As camadas superiores que vão definir o comportamento do sistema quando um item é adicionado. Em vez de usar as alternativas da questão, manter um estado com uma lista de FormAnswers

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                            )
Editar somente o item da lista que mudou não altera o estado? Se sim pode manter assim, se não basta modificar apenas o item que foi editado

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +}
Botão pode ser um IconButton simples, só precisa ser renderizado no menu expandido e quando questionAlternative for substituída por FormAnswer. A unidade de medida pode ser recebida como parâmetro do componente para evitar valores hardcoded

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +            }
Toda essa parte de renderizar uma FormAnswer específica pode ser movida para um composable menor para facilitar a legibilidade, a única desvantagem é que ele deve receber o callback de atualização da resposta também

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
Mudar a cor dos textos nos textfields para onSurface, atualmente a visualização não fica adequada no modo escuro
![Sem título](https://github.com/user-attachments/assets/d0a3547b-ae06-4c63-8835-d6d4695447a4)

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                    )
Utilizar recurso de string, valor também não é atualizado quando o texto é digitado no componente não expandido

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
> +                    )
Quando o meu estiver expandido e nenhum campo do cabeçalho for editável, talvez seja melhor usar Chips do jetpack compose para não ter que definir um `onValueChange` vazio. Na forma atual os text fields não mudam o valor, mas o usuário ainda consegue digitar neles
https://developer.android.com/develop/ui/compose/components/chip?hl=pt-br

2024-12-14 13:58 UTC, Joao-Pedro-P-Holanda commented on app/src/main/java/io/github/sustainow/presentation/ui/components/MultiFieldQuestionCard.kt
Mudar o tipo de teclado nos textfields numéricos, e mostrar supportingText para valores incorretos. Componente de seleção numérica já implementa isso e pode ser usado de exemplo

2025-01-24 11:09 UTC, Joao-Pedro-P-Holanda approved these changes
Mergeando incompleto para ser refatorado com as outras questões

2025-01-24 13:24 UTC, Francisco-Paulino-Arruda-Filho approved these changes

2025-01-24 13:25 UTC, merged